name: Split releases

on:
  release:
    types: ['published']

concurrency:
  group: split

env:
  GH_TOKEN: ${{ secrets.SPLITTER_ACCESS_TOKEN }}

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - { namespace: BunnyTransport, repo: bunny-transport }
          - { namespace: Demo, repo: demo }
          - { namespace: DoctrinePersistence, repo: doctrine-persistence }
          - { namespace: Message, repo: message }
          - { namespace: MessageBus, repo: message-bus }
          - { namespace: PdoPersistence, repo: pdo-persistence }
          - { namespace: TelephantastBundle, repo: telephantast-bundle }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          split_sha=`git subtree split --prefix=src/${{ matrix.package.namespace }}`
          repo_url="https://${{ secrets.SPLITTER_ACCESS_TOKEN }}@github.com/telephantast/${{ matrix.package.repo }}.git"
          if [ -z $(git ls-remote --tags "$repo_url" | grep "$split_sha") ]; then \
            gh release create ${{ github.ref_name }} \
              --repo typhoon-php/${{ matrix.package.repo }} \
              --target "$split_sha" \
              --generate-notes \
              --notes '[Full release information in Telephantast monorepo](https://github.com/telephantast/telephantast/releases/tag/${{ github.ref_name }}).'; \
          fi
